### ISSUE TITLE
Novos XMLTV's

### ISSUE THREAD

**Issue by migueltarga** [adrielcardoso/socialcine-server-api#1]
Onde consigo novos xmltvs?
obrigado

**Comment by adrielcardoso** [comment]
entra em contato com esse empresa.
http://www.xmltv.com.br/

qual a ideia man, manda ai

**Comment by migueltarga** [comment]
Possuo um aplicativo pra Android, e queria implementar EPG,
estava olhando varios sites que possuem programacao, consegui uns JSON e cheguei nesse seu projeto tbm, e fiquei curioso para saber onde conseguiu.

Obrigado por responder bro!

**Comment by adrielcardoso** [comment]
show man.
se ficar bilionário não esquece da font rsrs.

depois manda o link do app da store.  abc.

**Comment by migueltarga** [comment]
ahahahahahah, pode deixar.

https://play.google.com/store/apps/details?id=me.targa.iptvbr

esse eh o app antigo, fiz pra aprender um pouco de java, e acabou fazendo "sucesso", apesar de ele nao ter nenhuma info como funciona e tals.. ai o povo da 1 estrela pq nao sabe usar.

mas estou criando uma versao nova, e quero colocar em pratica tudo que aprendi.
